apiVersion: v1
kind: ReplicationController #--------------------------> 1
metadata:
   name: Tomcat-ReplicationController #--------------------------> 2
spec:
   replicas: 3 #------------------------> 3
   template:
      metadata:
         name: Tomcat-ReplicationController
      labels:
         app: App
         component: neo4j
      spec:
         containers:
         - name: Tomcat #- -----------------------> 4
           image: tomcat: 8.0
           ports:
            - containerPort: 7474 #------------------------> 5