apiVersion: v1
kind: Podmetadata:
  creationTimestamp: "2020-03-20T16:51:49Z"
  labels:
    name: app
  name: app
  namespace: elastic-stack
  resourceVersion: "683"
  selfLink: /api/v1/namespaces/elastic-stack/pods/app  uid: a7e5e5ec-2b24-451f-a434-1a12cd5d59e8
spec:
  containers:
  - image: kodekloud/event-simulator
    imagePullPolicy: Always
    name: app
    resources: {}
    terminationMessagePath: /dev/termination-log    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /log
      name: log-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-6d22b
      readOnly: true
  - name: sidecar
    image: kodekloud/filebeat-configured
    volumeMounts:
    - mountPath: /var/log/event-simulator/
      name: log-volume
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: node01
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /var/log/webapp
      type: DirectoryOrCreate
    name: log-volume
  - name: default-token-6d22b
    secret:
      defaultMode: 420
      secretName: default-token-6d22b
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-03-20T16:51:49Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-03-20T16:52:58Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-03-20T16:52:58Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-03-20T16:51:49Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://82bdc0cd07877bdf81a8e5ec245414d9d67bc4a581b11aa253df2dc30c68c221
    image: kodekloud/event-simulator:latest
    imageID: docker-pullable://kodekloud/event-simulator@sha256:1e3e9c72136bbc76c96dd98f29c04f298c3ae241c7d44e2bf70bcc209b030bf9
    lastState: {}
    name: app
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-03-20T16:52:57Z"
  hostIP: 172.17.0.53
  phase: Running
  podIP: 10.88.0.6
  podIPs:
  - ip: 10.88.0.6
  qosClass: BestEffort
  startTime: "2020-03-20T16:51:49Z"